jupyter-widgets/ipyleaflet

ipyleaflet/__init__.py, ipyleaflet/leaflet.py, js/package.json, js/src/jupyter-leaflet.js
This is adding mouse events to geoJSON layers.
=> Geojson click

js/src/index.js, js/src/jupyter-leaflet.js, js/webpack.config.js
@blink1073 this is what we talked about. I added some comments about the webpack issues in the webpack config file.
This is the version that generates the corrupted files.
=> Use webpack to bundle the marker static resources.

README.md
Instructions for a conda installation.
=> Conda installation

.gitignore, ipyleaflet/__init__.py, ipyleaflet/leaflet.py, js/package.json, js/src/embed.js, js/src/index.js, js/src/jupyter-leaflet.js, js/src/labplugin.js, js/src/notebook.js, js/webpack.config.js
=> Jupyterlab Extension

MANIFEST.in, setup.py
Also adding package data for non sys-prefix install.
=> Add Jupyterlab data files for wheel

js/package.json, setup.py
=> updating to newer versions of leaflet

examples/Primitives.ipynb, ipyleaflet/leaflet.py, js/package.json, js/src/index.js, js/src/jupyter-leaflet.js
Fixes #63, using https://github.com/Leaflet/Leaflet.markercluster
=> Add a marker cluster feature

ipyleaflet/leaflet.py
=> Add version numbers to all widget classes.

ipyleaflet/leaflet.py, js/src/jupyter-leaflet.js
Removing view-related data attributes that leaked into the model and were causing bugs when multiple views of the same map had different sizes.
=> Resolve view abstraction leak

js/src/jupyter-leaflet.js, js/webpack.config.js
Cf https://github.com/Leaflet/Leaflet/issues/4968
=> Workaround webpack marker issue

js/src/jupyter-leaflet.js
- Use a `dirty` flag on the view to prevent sub-pixel center changes computed by leaflet.js to be applied to the model.
- Use `flyTo` instead of `setZoom` to apply model's center value upon change of zoom. Indeed, subpixel errors at low zoom level may correspond to large error at the new higher zoom level.
=> Prevent subpixel leaflet errors to impact model values

js/src/jupyter-leaflet.js
https://github.com/ellisonbg/ipyleaflet/issues/121
=> typo when updating bounds

examples/Video.ipynb, ipyleaflet/leaflet.py, js/src/jupyter-leaflet.js
I added a `VideoOverlay` feature and created a Video example notebook.
=> Video overlay

examples/Animation.ipynb, examples/CustomTMS.ipynb, examples/Side-by-side.ipynb, examples/SplitMap.ipynb, examples/strava-side.ipynb, ipyleaflet/leaflet.py, js/package-lock.json, js/package.json, js/src/jupyter-leaflet.js
This is a rebased version of #60. Cannot be merged at the moment since last release of `side-by-side` does not support leaflet 1.x. However their master branch does so we can wait for them to release a new version cf https://github.com/digidem/leaflet-side-by-side/issues/20.
=> Side by side

js/src/jupyter-leaflet.js
=> Fix race condaition for double-click zoom

ipyleaflet/leaflet.py, js/src/jupyter-leaflet.js
Fixes #140 
Fixes inheritance of Circle and CircleMarker classes according to leaflet implementation
=> Fix Circle and CircleMarker classes inheritance

js/src/jupyter-leaflet.js
=> Fix location update for CircleMarker and Circle classes

examples/LayerGroup.ipynb, ipyleaflet/leaflet.py, js/src/jupyter-leaflet.js
=> Fix layer group

examples/Primitives.ipynb, ipyleaflet/leaflet.py, js/src/jupyter-leaflet.js
=> Add support to popup

ipyleaflet/leaflet.py
=> Remove useless attribute

ipyleaflet/leaflet.py, js/src/jupyter-leaflet.js
- PEP8 compliancy (except for lines too long)
- Remove useless overloaded attributes
- Add missing default values
- Comment code
=> Clean and comment code

examples/Numpy.ipynb, examples/Video.ipynb, ipyleaflet/leaflet.py, js/src/jupyter-leaflet.css, js/src/jupyter-leaflet.js
Update with latest Rasterio (RESAMPLING -> Resampling).
Add image interpolation option to support nearest neighbor mode.
=> Numpy example update

README.md
=> Add section for Docs

examples/Wind_velocity.ipynb, ipyleaflet/__init__.py, ipyleaflet/leaflet.py, ipyleaflet/xarray_ds.py, js/package-lock.json, js/package.json, js/src/jupyter-leaflet.js, setup.py
The velocity data is just read from a JSON file. It might be worth looking at https://github.com/benbovy/xvelmap for xarray integration.
=> Add leaflet-velocity layer

js/src/jupyter-leaflet.js
I have a use-case where I wanted to dynamically update the image url of a layer, which seemed to be missing. Any reason not to add it here?
=> Update image/video layer upon URL change.

examples/DrawControl.ipynb, ipyleaflet/leaflet.py, js/src/jupyter-leaflet.js
=> Implement clear methods for DrawControl

ipyleaflet/leaflet.py, js/src/jupyter-leaflet.js
https://github.com/Leaflet/Leaflet/blob/e5a3d5ecc360af77e291451172c60d4e3807cf72/src/layer/FeatureGroup.js#L26
somehow related to #68
=> A feature group should be a layer group

examples/BaseMap.ipynb, js/src/jupyter-leaflet.css
=> Fix map layout

examples/Heatmap.ipynb, js/src/jupyter-leaflet.js
=> Fix heatmap locations update

docs/source/api_reference/marker_cluster.rst
Simple change in longitude values to make them in the more expected range between -180 and 180 degrees.
=> Change example longitudes to more reasonable values inside (-180, 180)

docs/source/api_reference/embed_widgets/marker_icon.html, docs/source/api_reference/icon.rst, docs/source/api_reference/marker.rst, docs/source/index.rst, ipyleaflet/leaflet.py, js/package.json, js/src/jupyter-leaflet.js
How does this look?
Its my first time contributing to jupyter-widgets. 
Changes
------------------
* Added capability to rotate markers with leaflet plugin  https://github.com/bbecquet/Leaflet.RotatedMarker
* Added a widget model and view for marker icons.
* Updated documentation for new features.
=> Rotate markers, Marker Icons

js/package-lock.json, js/src/jupyter-leaflet.js
@maartenbreddels it should fix #227
=> Fix style update for GeoJSON layer

ipyleaflet/leaflet.py, js/src/jupyter-leaflet.js
@arkanoid87 This should fix #92
=> Add mouse events to Layer class

environment.yml
example MarkerCluster.ipynb failed in mybinder.
=> added geopandas

ipyleaflet/leaflet.py, js/src/jupyter-leaflet.js
=> Set no_clip attribute to True by default

ipyleaflet/leaflet.py, js/src/jupyter-leaflet.js
=> Fix popup size

ipyleaflet/leaflet.py, js/src/jupyter-leaflet.js
Should fix #257
@davidbrochart Would you mind trying this implementation and telling me what you think? :)
=> Implement LocalTileLayer

js/src/jupyter-leaflet.css
=> Fix Map display in VBox

js/src/jupyter-leaflet.js
=> Fix icon issue

examples/WidgetControl.ipynb, ipyleaflet/leaflet.py, js/src/controls/WidgetControl.js, js/src/jupyter-leaflet.css, js/src/jupyter-leaflet.js
=> Widget control

examples/WidgetControl.ipynb, ipyleaflet/leaflet.py, js/package-lock.json, js/src/controls/Control.js, js/src/controls/FullScreenControl.js, js/src/controls/MeasureControl.js, js/src/controls/WidgetControl.js
=> Allow maps in WidgetControl

docs/source/conf.py
=> Workaround for #298

ipyleaflet/leaflet.py, js/package-lock.json, js/src/layers/Layer.js, js/src/layers/Popup.js
=> Match Leaflet popup style attributes

js/src/layers/Popup.js
=> Changing Popup attribute child 

environment.yml
So the [Velocity example](https://github.com/jupyter-widgets/ipyleaflet/blob/master/examples/Velocity.ipynb) works out of the box in Binder.
=> Add netcdf4 to environment.yml

docs/source/api_reference/map.rst
=> DOC: Add crs option on Map

README.md, docs/source/installation.rst
cc @fitoprincipe
This should fix #338
=> Improve installation documentation

examples/MapCursorStyle.ipynb, ipyleaflet/leaflet.py, js/src/Map.js, js/src/jupyter-leaflet.css, js/src/jupyter-leaflet.js
Trying to solve issue https://github.com/jupyter-widgets/ipyleaflet/issues/167
=> add MapStyle to change Map's css style, aiming to change the cursor type

ipyleaflet/leaflet.py, js/package-lock.json, js/package.json
Version 1.0.4, is currently most recent, this seems to fix some problems people
were having with DrawControl
=> Use latest version of leaflet-draw plugin

js/src/controls/LayersControl.js
=> Add layers control to map every time a layer is added

docs/source/api_reference/tile_layer.rst
Add the no-wrap option for the TileLayer with its default value.
=> Add doc for no_wrap option

docs/source/api_reference/choropleth.rst
=> choropleth doc improvement

examples/Select-GeoJson.ipynb
Hi,
I have added a very simple example how to use leaflet to select Features from GeoJSON...
=> Adding an example of selecting GeoJSON features by clicking on the leaflet layer

setup.py
=> Fix wrong requirement string

examples/Select-GeoJson.ipynb
This PR adds back a commit that has been removed from master by accident.
=> Add Select GeoJSON example

js/src/index.js, js/src/jupyter-leaflet.css, js/src/jupyter-leaflet.js, js/src/theme/labvariables.css, js/src/theme/materialcolors.css
=> Add jlab themes support

README.md, docs/source/api_reference/marker.rst, docs/source/index.rst, docs/source/usage.rst
cc. @deeplook 
This should fix #374 (Not really the original purpose of the issue, but I guess we conclude that there was missing information in the documentation)
=> Add Usage section in the docs

js/src/controls/WidgetControl.js, js/src/layers/Popup.js
=> Trigger before-attach events and fix popup display

ipyleaflet/leaflet.py, setup.py
=> Make geopandas an optional dependency

ipyleaflet/leaflet.py, js/src/layers/TileLayer.js
=> Feat : Add redraw method for TileLayer

examples/Choropleth.ipynb, examples/GeoJson_EU_on_hover.ipynb, js/src/layers/GeoJSON.js
Changing the GeoJSON.js file and send "feature" for on_hover method. 
You can also see how to use it in these notebooks examples :   GeoJson_EU_on_hover.ipynb  and Choropleth.ipynb
=> GeoJSON sending feature and example

js/src/Map.js
=> Fix issue when the view is not rendered yet

examples/GeoData_on_hover.ipynb, ipyleaflet/leaflet.py
Change the GeoData class in order to use on_hover.
You can also see how to use it in this notebooks example: GeoData_on_hover.ipynb
=> Geodata on hover

examples/Numpy.ipynb
* Updated USGS url for South America data download
* match changes in rasterio Dataset (`affine` property is obsoleted after rasterio 1.0)
=> Update examples/Numpy.ipynb 

README.md, docs/source/installation.rst
=> Add missing installation command

docs/source/api_reference/local_tile_layer.rst, ipyleaflet/leaflet.py, js/src/layers/LocalTileLayer.js, js/src/layers/TileLayer.js
=> LocalTileLayer fix + doc fix

ipyleaflet/leaflet.py
This maintains consistency with Map class.
=> Add substitute_layer to LayerGroup class

docs/source/api_reference/tile_layer.rst, ipyleaflet/leaflet.py, js/package-lock.json, js/package.json, js/src/jupyter-leaflet.js, js/src/layers/TileLayer.js
API is the following:
```python
from ipyleaflet import Map
m = Map(center=(46, 14), zoom=5, zoom_control=True)
m
l = m.layers[0]
l.show_loading = True
```
=> Add spinner when tiles are loading

ipyleaflet/leaflet.py
=> Remove on_displayed event listener

examples/ant_path.ipynb, ipyleaflet/leaflet.py, js/package-lock.json, js/package.json, js/src/jupyter-leaflet.js, js/src/layers/AntPath.js
=> Add leaflet-ant-path plugin

ipyleaflet/leaflet.py, js/src/layers/TileLayer.js
There is code of another approach I made. We can clean it up later.
=> add loading attribute to TileLayer

docs/source/conf.py
This will fix CSS issues (missing JLab CSS variables in the documentation)
=> Update HTMLManager in the documentation

examples/MapContainer.ipynb, js/src/Map.js, js/src/controls/DrawControl.js, js/src/controls/LayersControl.js, js/src/layers/GeoJSON.js, js/src/layers/Layer.js, js/src/layers/LayerGroup.js, js/src/layers/Marker.js, js/src/layers/MarkerCluster.js, js/src/layers/Popup.js, js/src/layers/TileLayer.js, js/src/layers/VideoOverlay.js, setup.py
=> Further the transition from es5

examples/GeoJson_EU_on_hover.ipynb
Signed-off-by: martinRenou <martin.renou@gmail.com>
=> Fix indentation

ipyleaflet/leaflet.py, js/src/Map.js
=> Allow passing a TileLayer as basemap

js/src/layers/Marker.js, js/src/layers/Popup.js
=> Fix Popup.initialize method

examples/ScaleControl.ipynb, ipyleaflet/leaflet.py, js/src/controls/ScaleControl.js, js/src/jupyter-leaflet.js
=> Add Scale control

js/src/layers/TileLayer.js, js/src/layers/WMSLayer.js, js/src/leaflet.js
=> Patch LeafletJS for replacing tiles instead of removing/adding when changing the tiles URL

docs/Makefile
Workaround for #488, see https://github.com/jupyter/jupyter-sphinx/pull/97
=> Doc: Workaround CSS issue

.travis.yml
=> Add Travis installation check

ipyleaflet/leaflet.py
Should fix https://github.com/jupyter-widgets/ipyleaflet/issues/409
=> Fix Choropleth class when using integer data

docs/Makefile, docs/requirements.txt, docs/source/conf.py, examples/VectorTiles.ipynb, ipyleaflet/leaflet.py
Some cleaning before the release
=> Release cleaning

js/package-lock.json, js/package.json, js/src/jupyter-leaflet.js, js/src/leaflet.js
=> Use leaflet-defaulticon-compatibility for icon image bundling

docs/source/api_reference/image_video_overlay.rst
I added an image overlay example and noted the relative path of image/video. #550
=> Added image overlay example

docs/source/api_reference/legend_control.rst, docs/source/index.rst, examples/LegendControl.ipynb, ipyleaflet/leaflet.py, js/src/controls/LegendControl.js, js/src/jupyter-leaflet.css, js/src/jupyter-leaflet.js
Add ipyleaflet-legend to ipyleaflet code base as LegendControl as discussed here : https://github.com/weatherforce/ipyleaflet-legend/issues/5 :)
=> Feature legend control

.travis.yml, ipyleaflet/leaflet.py
@sackh @omanges If you could tell me what you think and give it a try that would be super great. On my side it seems everything is working fine as expected, as well as the regression you were fixing @sackh
=> Refactor GeoJSON._get_data

docs/source/api_reference/basemaps.rst, docs/source/api_reference/map.rst, docs/source/usage.rst, ipyleaflet/leaflet.py
=> Add save to HTML method

ipyleaflet/leaflet.py
Hi @martinRenou, 
This change fixed issue #589. I have created a copy of the `style` dictionary so that it avoids updates of the last dictionary in each feature.
Please review.
=> fix for issue #589 GeoJSON style_callback

.gitattributes
This did not fix the "Used by" button.
=> Remove gitattributes

ipyleaflet/leaflet.py
Hi @martinRenou 
I have fixed this issue, I think this has happened when we fixed flake 8 errors.
I have renamed the variables now, it is working fine.
=> Fix for issue #618 - Removing layer also removes basemap

ipyleaflet/leaflet.py
Should fix https://github.com/jupyter-widgets/ipyleaflet/issues/373 and fix https://github.com/jupyter-widgets/ipyleaflet/issues/560
=> Fix GeoJSON click event

ipyleaflet/leaflet.py
=> Fix for KeyError: 'popup_anchor' and other traits of Icon

ipyleaflet/leaflet.py
Workaround for the discussion in #634
=> Fix icon attrs default values

js/src/controls/DrawControl.js
=> Fixed DrawControl position 

ipyleaflet/leaflet.py
Fix and issue mentioned in #657
=> GeoJSON: Fix data styling update

examples/Velocity.ipynb
=> Fix Velocity notebook

js/src/layers/GeoJSON.js
This will fix issue #666 
@martinRenou - Please review this.
I have tested this and it works also tested choropleth functionality as these are related.
=> Added better way to update GeoJSON data

examples/MarkerCluster.ipynb, js/src/layers/Marker.js
=> fixed tooltip popup for title of marker

examples/MarkerCluster.ipynb, js/src/layers/Marker.js
Reverts jupyter-widgets/ipyleaflet#677, see https://github.com/jupyter-widgets/ipyleaflet/issues/676
=> Revert "fixed tooltip popup for title of marker"

docs/source/api_reference/search_control.rst, ipyleaflet/leaflet.py, js/src/controls/SearchControl.js
@martinRenou - I have tested this, please review.
fix for #687
=> Made default value of zoom trait for SearchControl None, so it will not change by default

postBuild
Fixes #699 
Can be tested with:
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/jtpio/ipyleaflet/patch-1?urlpath=%2Flab)
=> Set --minimize=False on Binder

docs/source/api_reference/search_control.rst, examples/SearchControl.ipynb, ipyleaflet/leaflet.py, js/src/controls/SearchControl.js
@martinRenou - I have added callback for a searched feature in the GeoJSON layer. Please review.
This will address #702
=> Added callback functionality for seached GeoJSON feature in SearchControl

.github/workflows/main.yml
The CI is taking too much time
=> CI: Reduce build matrix

docs/source/api_reference/widget_control.rst, ipyleaflet/leaflet.py, js/src/controls/WidgetControl.js
To make WidgetControl background transparent as suggested in https://github.com/jupyter-widgets/ipyleaflet/issues/716
=> To make WidgetControl background transparent

README.md
=> Change license to MIT

.github/workflows/main.yml, js/src/layers/WMSLayer.js
=> Fix WMS layer options

README.md
Will allow for deep links to individual examples
=> Use proper headings in README

docs/source/related_projects.rst
@giswqs I added leafmap and updated the URL of geemap.
Let me know if that's fine!
=> Update related projects

setup.py
This fixes the `jupyter labextension develop .` command ran from the root dir
=> Remove logs from setup.py

ipyleaflet/leaflet.py, js/src/layers/MarkerCluster.js
Exposing disableClusteringAtZoom option #823.
=> Added disable_marker_clustering_at_zoom option

docs/requirements.txt, ipyleaflet/leaflet.py, setup.py
This will allow using ipyleaflet in jupyterlite (as shapely is not installable with micropip).
Fix #769
=> Remove shapely and branca dependencies

examples/MarkerCluster.ipynb, ipyleaflet/leaflet.py, js/src/layers/MarkerCluster.js
=> Added maxClusterRadius

examples/CanvasRenderer.ipynb, ipyleaflet/leaflet.py
Resolves #852 by introducing a new `Map` option `prefer_canvas` which passes down to the Leaflet map instance.
=> Added a new Map option "prefer_canvas".

examples/DrawControl.ipynb, examples/LegendControl.ipynb, examples/Transform.ipynb, ipyleaflet/leaflet.py
Fixed several topos using [codespell](https://github.com/codespell-project/codespell).
=> Fixed typo

ipyleaflet/__init__.py
Follow up of https://github.com/jupyter-widgets/ipyleaflet/pull/869
=> Added Colab support

docs/source/api_reference/search_control.rst, ipyleaflet/leaflet.py, js/src/controls/SearchControl.js
https://user-images.githubusercontent.com/21197331/144225514-02af3fa2-781d-43ea-90be-114b0db9332d.mp4
=> SearchControl: location found callback

js/src/controls/SearchControl.js, js/src/layers/ImageOverlay.js, js/src/layers/LayerGroup.js
=> Missing call to super.default

docs/source/related_projects/index.rst
Adds localtileserver to the related projects to help people visualize their large geospatial rasters with ipyleaflet: https://github.com/banesullivan/localtileserver
=> Add localtileserver to related projects

ipyleaflet/leaflet.py
Remove get and set decorators in LegendControl in leaflet.py.
=> Remove get and set decorators in LegendControl in leaflet.py.

js/src/Map.js
This resolves https://github.com/jupyter-widgets/ipyleaflet/issues/995
=> move _dragging from model value to attribute

CHANGELOG.md, docs/environment.yml, docs/source/index.rst, docs/source/ipyleaflet.ipynb, docs/source/jupyterlite_config.json
=> Update changelog for 0.17 and reintroduce embedded jupyterlite

.github/workflows/ui-tests.yml
This fixes the [Visual Regression CI failures](https://github.com/jupyter-widgets/ipyleaflet/runs/7250711786?check_suite_focus=true).
=> Pin nodejs=16, drop base setup

examples/Velocity.ipynb
Removed the unwanted character from Python code.
=> Removed the unwanted character from Python code.

docs/_static/main_stylesheet.css, docs/conf.py
Fix for the bug mentioned in [#1578](https://github.com/pydata/pydata-sphinx-theme/issues/1578)
=> Documentation: Fix CSS issue

python/ipyleaflet/ipyleaflet/velocity.py
This PR fixes the bug reported in https://github.com/jupyter-widgets/ipyleaflet/issues/1198
=> Fix velocity display_options bug

python/jupyter_leaflet/src/controls/MeasureControl.ts, python/jupyter_leaflet/src/definitions/leaflet-extend.d.ts
=> Add workaround for MeasureControl map panning bug
