jupyter-widgets/ipyleaflet

leafletwidget/static/leaflet.js

This fixes the issue where the leaflet draw controls don't appear due to a missing reference to the L variable (Leaflet is non-AMD).

Correct leaflet shim

---

js/src/embed.js
js/webpack.config.js

This should make the marker static URL work when the baseURL is not `/`.

Dynamic setup of webpack public path based on base Url

---

ipyleaflet/leaflet.py
js/README.md
js/src/jupyter-leaflet.js

needed to avoid insecure content warnings when loaded on https pages (e.g. jupyter.org)

use https everywhere

---

ipyleaflet/leaflet.py

Moving the default tile information to the Map object allows for adding additional TileLayer layers to a Map without needing to override the default attribution text.

Move default tile URL and attribution to the Map object's default tiles

---

ipyleaflet/_version.py

This is required to work with `jupyter-leaflet` `0.5.0`.

Fixup extension version

---

js/src/jupyter-leaflet.js

Calling `InvalidateSize` upon `resize` and `after-show`. It seems that the latter is unnecessary because the resize event is triggered right after.
cc @blink1073

InvalidateSize upon phosphor resize event

---

examples/Primitives.ipynb
ipyleaflet/leaflet.py
js/src/jupyter-leaflet.js

- Using readonly traits instead of properties for `south, west, east, north`, so that users can setup change handlers to them.
- Removal of the `default_tiles` trait, which is absorbed in the default handler for the layers trait.
- Allow for `add_layer` to take a basemap instead of a fully built tile layer. 
This should go into `0.7` since it is strictly a backward incompatible change.

Modernize traitlets API

---

examples/CustomTMS.ipynb

Removes the use of Map.default_tiles which was removed in Release 0.7.0.

Update CustomTMS examples use of default tiles.

---

ipyleaflet/leaflet.py
js/src/jupyter-leaflet.js

Radius attribute is now an option for CircleMarker and Circle classes. Fixing the update of the radius for CircleMarker. I did the same changes for the Circle class, but it still doesn't work because of an issue in Leaflet: https://github.com/Leaflet/Leaflet/pull/6128

Fix issue with CircleMarker radius

---

ipyleaflet/leaflet.py
js/src/jupyter-leaflet.js

It seems like the clickable attribute of Marker class is useless. It's never used on the javascript side, and not part of the options in Leaflet: https://github.com/Leaflet/Leaflet/blob/master/src/layer/marker/Marker.js

Remove useless clickable attribute of Marker class

---

README.md
docs/source/installation.rst

I ran into an issue that ipyleaflet would only display in `jupyter
notebooks` and not `jupyter lab`. This details the additional step
needed to get it working on Jupyterlab.
This addresses these two issues #168  and #173

Adding documentation about getting jupyterlab ipyleaflet working

---

README.md
postBuild

I previously submitted a pull request for improving the documentation on using ipyleaflet with jupyterlab. In fact I needed it to work for a binder example project of my own. So I wanted to offer a minimal pull request that will set the default binder launch button to use jupyterlab instead of jupyter notebooks. 
The only addition required is a [postBuild](https://mybinder.readthedocs.io/en/latest/using.html#postbuild) file for adding the two labextensions: jupyter-manager and ipyleaflet.  Description of what a postBuild file is [here](https://mybinder.readthedocs.io/en/latest/using.html#postbuild)
You may use the following link to test of the binder jupyterlab notebook examples before the pull request. I have already tested that all the example notebooks run and display properly in …

Switch to jupyterlab for binder examples

---

ipyleaflet/basemaps.py

This fixes two minor issues with the CartoDB basemap dictionaries:
- URL and attribution values in `basemaps.CartoDB.Positron` were incorrect. They appeared to have been copied from `basemaps.MtbMap` without modification. 
- Maximum zoom level value in `basemaps.CartoDB.DarkMatter` did not match the supported range from 0 to 20 (see https://github.com/CartoDB/basemap-styles). Value is now also consistent across CartoDB basemaps.
First time contributing to ipyleaflet. Hope it looks ok.

Fix CartoDB basemaps

---

js/src/controls/LayersControl.js
js/src/controls/MeasureControl.js

Controls are added to the Map by the Map itself already. No need to add it from
the control implementation.

Remove useless code

---

docs/source/api_reference/embed_widgets/layers_control.html
docs/source/api_reference/embed_widgets/map.html
docs/source/api_reference/embed_widgets/split_map_control.html
ipyleaflet/basemaps.py

- Updating GIBS URLs to use the offical endpoints and a more recent date.
- Adding VIIRS True Color Corrected Reflectance.
- Updating VIIRS Earth at Night to use the newer layer.  Technically "Black Marble", but still the earth at night.

Changes for NASA GIBS sample imagery endpoints.

---

js/src/index.js
js/src/leaflet.js

Leaflet has a no-conflict mode where if `L` is already defined, it can be restored as `window.L` with Leaflet assigned to another variable of choice.
In this specific case, if another Jupyter widget is already trying to use it's own version of Leaflet, loading ipyleaflet will redefine the existing Leaflet library, and any control or plugins that were previously loaded into the first Leaflet namespace will disappear.
This fix checks to see if `L` is already defined, and if it is, it uses `Leaflet.noConflict()` to restore the previous `L` and moves ipyleaflet's Leaflet to the variable `ipyL`.
Users who only use ipyleaflet will not be impacted as Leaflet will load as `L` in the standard manner.

Load Leaflet in no-conflict mode if L is already defined

---

setup.py

a simple change to allow newer versions of xarray to be installed alongside ipyleaflet. Related issues: https://github.com/jupyter-widgets/ipyleaflet/issues/297, https://github.com/jupyter-widgets/ipyleaflet/pull/221, https://github.com/jupyter-widgets/ipyleaflet/issues/212

removed xarray upper bound

---

ipyleaflet/leaflet.py
js/package-lock.json
js/src/Map.js
js/src/layers/WMSLayer.js

This should fix #311 and #255.
cc @bizzarks @kafonek
This will allow you to create a map specifying the crs:
```python
m = Map(crs='EPSG4326')
```

Add crs option to WMSLayer and Map

---

js/src/jupyter-leaflet.css

A small / simple change to fix the following glitch when using the JupyterLab Dark theme:
In the context of the classic notebook, the background will default to the original `#ffffff` value.

Use JLab background color for widget controls

---

postBuild

Binder images currently use JupyterLab 0.35 by default.
The compatible version for `@jupyter-widgets/jupyterlab-manager` is 0.38.

Bump jupyterlab-manager to 0.38

---

ipyleaflet/basemaps.py

I think that this was a typo given that OpenTopoMap is called using ```basemaps.OpenTopoMap```

Change name of OpenTopoMap from 'OpenTopMap' to 'OpenTopoMap'

---

js/src/index.js

Geojson extension uses the same Leaflet lib version in jupyterlab, so calling `noConflict` is not needed when global `L` hasn't really changed, fixes #337.

Use more robust check before using noConflict() mode

---

ipyleaflet/leaflet.py
js/src/Map.js

Adding a two way `fullscreen` parameter, setting it to `True` puts map in to
full screen mode, and setting it to `False` exits full screen mode. Current
state is observable via this parameter as well.
Typically browser will not allow to enter full screen if the event has not
been triggered by the user, so this can only be used in response to the user
action like a button click.
Entering fullscreen mode via custom ui click doesn't work, looks like
safari expects fullscreen request and UI interaction that triggers it to happen
in the same animation frame and not just in "close enough in time". Observing
fullscreen state and exiting it does work however. And it's an important use
case, for example if user completes some input in full screen mode it might be
desirable to exit fullscreen at …

Expose fullscreen control/state

---

js/src/layers/GeoJSON.js

There were two problems:
1. `_.extend(undefined, {..})` is `undefined`, so style would not apply to geojson objects without style defined.
2. New style would revert to original after every hover, since initial style was captured at
construction and was never updated.
This addresses issue #341.

Fix styling problems for GeoJSON

---

ipyleaflet/leaflet.py

This add the [noWrap](https://leafletjs.com/reference-1.5.0.html#gridlayer-nowrap) option for the TileLayer.
Whether the layer is wrapped around the antimeridian. If true, the TileLayer will only be displayed once at low zoom levels.

Add no_wrap option for TileLayer

---

js/src/controls/FullScreenControl.js
js/src/controls/LayersControl.js

Options were not given to JS objects

Fixes #367 : Options are now given to the JS control

---

ipyleaflet/leaflet.py
js/src/Map.js
js/src/controls/ZoomControl.js
js/src/jupyter-leaflet.js

The ZoomControl is the zoom control added when you create a map with the option `zoom_control=True`.
The problem was you could not move it on the map.
Now you can do it :
```
import ipyleaflet as lf
m = lf.Map(zoom=1, zoom_control=False) #Deleting the original from the map
control = lf.ZoomControl(position='topright')
m.add_control(control)
m
```

Add ZoomControl has an Ipyleaflet.Control

---

ipyleaflet/leaflet.py

It's an oversight in the `__init__` method of the class Map. So when the map is created, the ZoomControl too if `zoom_control=True`

Add missing add of the ZoomControl in __init__

---

ipyleaflet/basemaps.py

This will fix the following warnings when the notebook server is running behind HTTPS but the tiles are served over HTTP:
```
Loading mixed (insecure) display content “http://stamen-tiles-a.a.ssl.fastly.net/terrain/10/533/366.png” on a secure page
```

Load Stamen tiles over HTTPS

---

js/package.json

Add keywords to allow for package to be visible in JupyterLab extension manager

---

ipyleaflet/leaflet.py

Comply with changes made in traitlets [version 4.1](https://traitlets.readthedocs.io/en/stable/changelog.html?highlight=tag#id9).
Addresses: https://github.com/jupyter-widgets/ipyleaflet/issues/414

Silence traitlet deprecation warnings

---

ipyleaflet/leaflet.py

Following discussion https://github.com/jupyter-widgets/ipyleaflet/issues/414#issuecomment-539007144
There is still one DeprecationWarning to fix in traittypes.Dataset (dtype should be set in a tag() method)

Fix some DeprecationWarning

---

js/src/layers/Polyline.js

For `Polyline` and `Polygon`, `locations` was not synced between Python and JS. This fix allows to do from Python:
```
polygon.locations = ((34.95100201839405, -78.10704956054689),
(34.95100201839405, -76.78457031250001),
(34.49897808891371, -76.78457031250001),
(34.49897808891371, -78.10704956054689))
```
and have it reflected on the map.

Sync locations

---

examples/Transform.ipynb
ipyleaflet/leaflet.py
js/package-lock.json
js/package.json
js/src/layers/Layer.js
js/src/layers/Path.js
js/src/layers/Polyline.js
js/src/leaflet.js

This PR gives the possibility to transform (i.e. rotate and scale) and drag e.g. polygons. It vendors [Leaflet.Path.Transform](https://github.com/w8r/Leaflet.Path.Transform) and [Leaflet.Path.Drag](https://github.com/w8r/Leaflet.Path.Drag) because of bugs that could not be fixed upstream.
The `examples/Transform.ipynb` notebook illustrates the API.

Add Leaflet.Path.Transform

---

ipyleaflet/leaflet.py
js/src/layers/GeoJSON.js

Before this commit GeoJSON points where always rendered as 'map pins'.
Now users can pass all CircleMarker options to `GeoJSON` using the
`point_style` argument. If the argument is present and non-empty,
points will be rendered using CircleMarkers. If the argument is
ommitted or empty, points are rendered as 'map pins'.
This could serve as a solution for #188 and #362.

Allow rendering GeoJSON points with CircleMarkers.

---

js/src/layers/Layer.js

Should fix #447 
@PBrockmann the following code should do what you want with this branch.
```python
from ipywidgets import HTML
from ipyleaflet import Map, Marker, Popup, CircleMarker
center = (52.204793, 360.121558)
m = Map(center=center, zoom=9, close_popup_on_click=False)
#=============================================
marker1 = Marker(location=(52.1, 359.9))
m.add_layer(marker1)
message1 = HTML()
message1.value = "Hello 1"
marker1.popup = Popup(child=message1, auto_close=False)
#=============================================
marker2 = Marker(location=(52.1, 360.9))
m.add_layer(marker2)
message2 = HTML()
message2.value = "Hello 2"
marker2.popup = Popup(child=message2, auto_close=False)
m
```

Add support for setting layer.popup to a Popup instance

---

examples/AwesomeIcons.ipynb
examples/bars.json
ipyleaflet/leaflet.py
js/package-lock.json
js/package.json
js/src/jupyter-leaflet.js
js/src/layers/AwesomeIcon.js
js/src/leaflet.js

Related to https://github.com/jupyter-widgets/ipyleaflet/issues/83, it does not add automatic support in the GeoJSON layer though.

Add support for font-awesome icons in Markers

---

ipyleaflet/leaflet.py

This prevents an error with `self.zoom_control_instance` not existing.
Same fix for the attribution control.

Add zoom_control_instance default value

---

docs/source/api_reference/circle.rst
docs/source/api_reference/circle_marker.rst
docs/source/api_reference/polygon.rst
docs/source/api_reference/polyline.rst
docs/source/api_reference/rectangle.rst
ipyleaflet/leaflet.py
js/src/layers/Path.js

This PR fills circle marker and other objects with the same color as the stroke color except for the opacity.
```python
from ipyleaflet import CircleMarker, Map
m = Map()
m.add_layer(CircleMarker(color='#d9a89c', fill_opacity=0.5, radius=100))
m
```
|  w/o PR  |  w/ PR |
| ---- | ---- |
| ![before](https://user-images.githubusercontent.com/13291527/75056864-2ca96b80-551b-11ea-826d-e66b6e82eeda.png) | ![after](https://user-images.githubusercontent.com/13291527/75056885-3a5ef100-551b-11ea-894a-5d4b609c030d.png) |
In Leaflet, the value of `Path`'s `fillColor` option defaults to its `color` value as is documented [here](https://leafletjs.com/reference-1.6.0.html#path-fillcolor). So I modified ipyleaflet accordingly.
IMHO this would be the behavior users find comfortable (at least I do), but …

Sync Path's fill_color with color

---

examples/DrawControl.ipynb

Renamed the positional argument from `self` to `target` to avoid confusion.

Renamed positional argument for handle_draw()

---

examples/DropdownControl.ipynb
ipyleaflet/basemaps.py

I discovered this typo when trying to loop through the basemaps using the name attribute. `MidsTerraBands721CR` should be corrected to `ModisTerraBands721CR`.
```
from ipyleaflet import basemaps
for item in basemaps.values():
try:
basemap = 'basemaps.{}'.format(item['name'])
print(eval(basemap))
except:
for sub_item in item:
basemap = 'basemaps.{}'.format(item[sub_item]['name'])
print(eval(basemap))
```

Fixed basemap name typo

---

docs/source/api_reference/map.rst
docs/source/api_reference/widget_control.rst

Corrected two typos and added `substitute_layer` to the Map methods.

Fixed typos in docs

---

.gitattributes

This should fix the "used by" button

Make Github ignore js files

---

js/package.json

fixing this issue : https://github.com/jupyter-widgets/ipyleaflet/issues/562

Add missing dependencies: @phosphor/messaging @phosphor/widgets

---

ipyleaflet/leaflet.py

The VectorTile layer is actually not working in the latest release (my fault :confused:), the constructor was calling a non-existing method
@omanges

Fix VectorTile layer

---

ipyleaflet/leaflet.py

There was small bug in PR #559  if `style `is not present in input geojson properties, it fails with KeyError while updating style, Hence I added check for it. If style is present in input geojson properties then update the style provided by the user else assign the style.
e.g. from CountriesGeojson notebook
```python
import ipyleaflet as ipyl
import ipywidgets as ipyw
import json
map = ipyl.Map(center=[53.88, 27.45], zoom=4)
label = ipyw.Label(layout=ipyw.Layout(width='100%'))
with open('./europe_110.geo.json') as f:
data = json.load(f)
layer = ipyl.GeoJSON(data=data, hover_style={'fillColor': 'red'}, style = {'color': 'green', 'opacity':1, 'weight':1.9, 'dashArray':'9', 'fillOpacity':0.1})
```
This was failing with `KeyError` `style`
I have handled this in my changes.
@martinRenou - …

bug fix for the PR #559 which was raised for issue #555

---

ipyleaflet/leaflet.py
setup.py

Removes `xarray` from the dependencies of ipyleaflet.
Although ipyleaflet has `xarray` listed in its `install_requires` I'm not exactly sure why it needs this dependency. It would be great if when I installed ipyleaflet, I didn't also have to install `xarray` (which, in turn, pulls in `pandas`) as a transitive dependency.

Remove xarray dependency 

---

docs/source/api_reference/velocity.rst
ipyleaflet/leaflet.py
ipyleaflet/velocity.py

`Velocity` is not imported by default anymore, it has to be explicitly imported with:
```python
from ipyleaflet.velocity import Velocity
```
If `xarray` is not installed, it raises `ModuleNotFoundError: No module named 'xarray'`.
Fixes #578

Fix Velocity import

---

ipyleaflet/leaflet.py

Fixes #570 by removing `_update_bounds`.

Fix overwriting of colormap ranges for Choropleth

---

examples/SearchControl.ipynb
ipyleaflet/leaflet.py
js/package.json
js/src/controls/SearchControl.js
js/src/jupyter-leaflet.js
js/src/leaflet.js

Hi @martinRenou,
I have added changes for SearchControl implementation.
Please review.

#534 - Code changes for Search Control feature

---

ipyleaflet/leaflet.py
js/src/Map.js

It can be useful to retrieve the URL of the browser window when we want to serve local tiles with `LocalTileLayer` through a custom Jupyter server handler.

Add window_url attribute to Map

---

ipyleaflet/leaflet.py
js/src/Map.js

Similar to the `bounds` read-only attribute, but in projected pixel coordinates instead of lat/lon coordinates (see https://leafletjs.com/reference-1.0.3.html#map-getpixelbounds).
While `bounds` is `((south, west), (north, east))`, `pixel_bounds` is `((left, top), (right, bottom))` to respect the Leaflet convention.

Add pixel_bounds to Map

---

ipyleaflet/projections.py

This is applying [this change](https://github.com/jupyter-widgets/ipyleaflet/issues/612#issuecomment-641761444).
@betolink I also changed the comment to `origin and bounds for 250m resolution` instead of 500m, is this correct?
Should we do the same for `EPSG:3031`?

Fix EPSG:3413 and EPSG:3031

---

ipyleaflet/leaflet.py

This PR implements the [`__geo_interface__` spec][spec] for `GeoJSON`, `Choropleth`, and `GeoData`. For `GeoData` we fall back to `geopandas` implementation on the `GeoDataFrame`.
Note that as is the convention with GeoDataFrame a` {'type': 'FeatureCollection', ...}` can be returned. This is not explicitly stated in the spec but the comments lobby for it and ask the geopandas contributors to expand on their approach.
[spec]: https://gist.github.com/sgillies/2217756
This is my first contribution to the project so I appreciate your attention and  patience!

Implement __geo_interface__ for relevant classes

---

js/src/Map.js
js/src/layers/Heatmap.js
js/src/layers/Layer.js
js/src/layers/Path.js
js/src/layers/Velocity.js

Fix option update

---

ipyleaflet/leaflet.py

This was resulting in some issues when panning:

Fix bounds type

---

setup.py

I checked that `examples/Choropleth.ipynb` works fine with `branca==0.4.1`.
Fixes #638

Pin branca>=0.3.1,<0.5

---

setup.py

@davidbrochart  - We need to add the dependency of shapely, as geopandas is the only dependency for building docs, hence docs build is not failing.
When I tested WKT functionality geopandas was already installed in my env hence it did not fail.
Now, when I created a new environment from scratch it fails as shapely is not added as a dependency. Hence adding it as a dependency.

Add dependency of shapely separately as Geopandas is dependency for building docs

---

docs/source/api_reference/geodata.rst

Add documentation for the point_style attribute that enables CircleMarkers on GeoData and GeoJSON point data per https://github.com/jupyter-widgets/ipyleaflet/pull/439#issuecomment-690846505 and https://github.com/jupyter-widgets/ipyleaflet/commit/6d59f4fcefaba112433d9e31a8e3671bd7037f21

Update geodata.rst to add point_style attribute

---

docs/source/api_reference/map.rst
ipyleaflet/leaflet.py

It is not implemented using Leaflet's [fitBounds method](https://leafletjs.com/reference-1.7.1.html#map-fitbounds) (see issues below), but by iteratively changing the zoom level and checking the bounds (which is the maximum bounds of all map views).
Fixes #96 
Fixes #529

Add Map.fit_bounds(bounds)

---

docs/source/api_reference/magnifying_glass.rst
docs/source/index.rst
examples/MagnifyingGlass.ipynb
ipyleaflet/leaflet.py
js/src/jupyter-leaflet.css
js/src/jupyter-leaflet.js
js/src/layers/MagnifyingGlass.js
js/src/leaflet-magnifyingglass.js
js/src/leaflet.js

[WIP] Add MagnifyingGlass layer

---

docs/source/api_reference/map.rst
ipyleaflet/leaflet.py

The `fit_bounds` method documentation `[[south, east], [north, west]]` is incorrect. It should be `[[south, west], [north, east]]`

Corrected fit_bounds docs

---

ipyleaflet/leaflet.py
js/src/controls/DrawControl.js

A data attribute is added to the model of the DrawControl widget. This allows the editable data layer to be changed programmatically from python. In addition, the attribute is automatically synced on each edit. The data attribute contains a
list dicts representing GeoJson objects. These are automatically converted into layers on the javascript side. It is possible to provide styling information by setting the property.style attribute.
The solution is not perfect as it does not give full control of the layers in the editable feature collection, but it does the job supporting many important use cases. In particular, it should solve issue #508.
This solution renders the DrawControl methods `clear`, `clear_polygons` obsolete.
```python
from ipyleaflet import Map, DrawControl
m = …
```

Added data attribute to DrawControl

---

README.md

Since without it a ValueError is raised (ref https://github.com/jupyter-widgets/widget-cookiecutter/issues/88)

Add --overwrite option for a dev install with JLab

---

ipyleaflet/basemaps.py

Simply replace `'...com//tiles/...'` by `'...com//tiles/...'` in Strava URLs

Fix for #865 : remove double slashes from Strava tile-URLs

---

docs/source/api_reference/map.rst

How to customise the layout is not obvious to new users not already familiar with ipywidgets. Screen sizes these days are such the default layout appears very horizontal and users appear often inclined to change the default height. The first experience to find out how can be smoothed a bit via documentation.

Add doc section for Map on basic layout options. Issue #750

---

examples/MarkerCluster-GeoJson.ipynb
ipyleaflet/leaflet.py
js/src/layers/MarkerCluster.js

Initial PR (needs review, maybe tests...) addessing #881
Made it possible to use a GeoJson layer as the data source for Marker Cluster, this makes it much faster when creating large numbers of markers (but not having bidirectional sync on individual Marker widgets).
Implemented by copying the behaviour of LayerGroup, it will simply attempt to add the model of whatever is provided in the marker list to the marker group: **this allows to mix geojson and Marker elements**.

Support GeoJson layer in MarkerCluster

---

docs/source/api_reference/velocity.rst

AFAICT the `import TileLayer` isn't used in the velocity example

rm used TileLayer

---

js/src/layers/TileLayer.js

This fixes a problem where if `show_loading` is `True` for a layer, and this layer is removed from the map prior to all tiles being loaded, the loading spinner for this layer continues to spin and is stuck on the map indefinitely.
It is noted that this tends to only be a problem for layers that take a good amount of time to load. Otherwise, under practical circumstances, it is unlikely that a layer `remove` event would fire before the `load` event. Therefore, to reproduce the problem described above, you will either need to find a tile layer that is slow to load, or otherwise temporarily disable the bit of code that stops the loading spinner upon the `load` event.
(Also, this is my first contribution here! If I should be opening an issue or something like that, let me know!)

Stop layer loading spinner when layer is removed

---

ipyleaflet/leaflet.py

Hi @martinRenou,
I am not sure why these code changes were not included in my PR #857 . As these are there to handle backward compatibility with the dictionary for basemap_to_tiles function.
Please review this. Without this, it will break if the user passes a simple dictionary as a basemap.
I added these changes in my forked branch but somehow did not see them in the PR.
https://github.com/sackh/ipyleaflet/blob/b741cb5cf9e86ae5f62bd1408de391ae6300b353/ipyleaflet/leaflet.py#L53

Added backward compatibility for dict basemaps

---

ipyleaflet/leaflet.py
js/src/layers/Popup.js

implemented open_popup and close_popup methods

---

js/src/controls/DrawControl.js

This fixes a bug wherein if a DrawControl is added and removed from a Map several times, callbacks start accumulating, resulting in duplicate layers.
For example, the following adds a DrawControl to the map, and adds a polygon to it:
```python
from ipyleaflet import Map, DrawControl
m = Map()
dc = DrawControl()
dc.data = [{
'type': 'Feature',
'properties': {
'style': {
'stroke': True,
'color': '#3388ff',
'weight': 4,
'opacity': 0.5,
'fill': True,
'fillColor': None,
'fillOpacity': 0.2,
'clickable': True
}
},
'geometry': {
'type': 'Polygon',
'coordinates': [
[[-0.104027, 0.005665],
[-0.069351, 0.023518],
[-0.062141, 0.00103],
[-0.104027, 0.005665]]
]
}
}]
m.add_control(dc)
m
```
Now, by removing and adding the DrawControl several times, we can see that it becomes much darker in opacity, …

Remove map callbacks when DrawControl removed from map

---

docs/source/controls/draw_control.rst
docs/source/controls/legend_control.rst
docs/source/controls/measure_control.rst
docs/source/controls/search_control.rst
docs/source/layers/layer_group.rst
docs/source/layers/popup.rst
docs/source/layers/vector_tile.rst
ipyleaflet/leaflet.py

In the documentation, fix some formatting issues in the attributes/attributes and methods/methods sections using autodoc.

Fix formatting issues in the doc for attributes and methods sections using autodoc

---

js/package.json

In js/package.json :
- Change 
"watch": "webpack --watch"
to
"watch": "run-p watch:src watch:labextension",
"watch:src": "webpack --watch",
"watch:labextension": "jupyter labextension watch ."
- Add in devDependencies : "npm-run-all": "^4.1.5",

Fix watch script in ipyleaflet

---

docs/source/controls/measure_control.rst
docs/source/layers/tile_layer.rst
examples/BaseMap.ipynb
examples/LayerGroup.ipynb
examples/MeasureControl.ipynb

In the documentation and in the examples' notebooks, replace any reference to Hydda by another basemap.

Docs remove hydda

---

js/src/Map.js

This ensures compatibility with ipywidgets 7 and 8.
In https://github.com/jupyter-widgets/ipyleaflet/pull/771, `processPhosphorMessage` was renamed to `processLuminoMessage`, but that renaming should be done at the ipywidgets 7/8 transition, as ipywidgets 7 does not support `processLuminoMessage`.
This PR implements @vidartf's compatibility shim for ipywidgets 7 and 8 that he posted in https://github.com/jupyter-widgets/ipywidgets/pull/3405#pullrequestreview-907246241
Fixes #773
Before this PR, notice the resize does not work in ipywidgets 7.7:
But after this PR, the resize does work in ipywidgets 7.7 (and should still work in ipywidgets 8):

Support both processPhosphorMessage and processLuminoMessage

---

docs/source/layers/tile_layer.rst
docs/source/map_and_basemaps/map.rst

Per the information in https://github.com/jupyter-widgets/ipyleaflet/issues/970 which I have tested and can confirm works, this PR updates the documentation to include an example of using multiple base layers on the TileLayer page, as well as a one sentence reference to it on the Map page.
Thank you!

Document use of multiple basemaps

---

docs/source/index.rst
docs/source/ipyleaflet.ipynb

In the documentation, in index.rst, change the try it online : replace the retrolite directive by 2 links to retro and lab.

Update try it online in the documentation.

---

js/amd-public-path.js
js/src/notebook.js
js/webpack.config.js

This updates the public path computation to use built-in require.js facilities, which means we no longer need to hardcode the public path, nor distinguish between the classic notebook extension and the CDN bundle.
See also https://github.com/jupyter-widgets/widget-cookiecutter/pull/103

Compute the public path automatically

---

js/src/Map.js

Fixes #977
It works, but when `dragging` is set the second time, we get this error in the console:
```
272.eb0d340….js:1 Error setting state: Cannot convert undefined or null to object
t.set_state	@	272.eb0d340….js:1
(anonymous)	@	272.eb0d340….js:1
Promise.then (async)		
t._handle_comm_msg	@	272.eb0d340….js:1
_handleCommMsg	@	jlab_core.fc632a0f38…32a0f38747f007842:2
_handleMessage	@	jlab_core.fc632a0f38…32a0f38747f007842:2
await in _handleMessage (async)		
(anonymous)	@	jlab_core.fc632a0f38…32a0f38747f007842:2
Promise.then (async)		
_onWSMessage	@	jlab_core.fc632a0f38…32a0f38747f007842:2
```
Looks like a low-level widget comm message error. Any idea @martinRenou ?

Rerender map when changing Map.dragging

---

examples/CountriesGeoJSON.ipynb
ipyleaflet/leaflet.py
js/src/layers/GeoJSON.js

Add visible attribute to GeoJSON layer

---

CHANGELOG.md
docs/source/changelog.rst
docs/source/controls/legend_control.rst
docs/source/index.rst
examples/LegendControl.ipynb
ipyleaflet/leaflet.py

This is a followup of #979, correcting our LegendControl docs where needed.
I left in a backwards-compatible shim for giving the name argument to the LegendControl, since that is likely the most common thing people would have to change.

Add deprecation warnings for API changes

---

docs/environment.yml

Pulling back a proper `jupyterlite-sphinx` release in the docs now that the fix has been released (currently at `0.6.0`).

Use the `jupyterlite-sphinx` release on ReadTheDocs

---

ipyleaflet/leaflet.py
js/src/layers/TileLayer.js

Add Leaflet's `zoomOffset` param for `TileLayer` class as `zoom_offset`.
Setting `zoom_offset=-1` is necessary in order to be able to support `tile_size=512`, which is the default tile size for Mapbox tiles. 
Fixes #31

Add zoom_offset param to TileLayer

---

docs/source/index.rst

Remove the retrolite directive in the documentation, since there are already the links and the buttons to click and make an online try.

Lazy-load the JupyterLite embedded page in documentation

---

docs/source/layers/index.rst
docs/source/layers/layer_like.rst
ipyleaflet/leaflet.py

I use `ipyleaflet` a ton with [localtileserver](https://github.com/banesullivan/localtileserver) and I was thinking it'd be convenient if `ipyleaflet.Map`'s `add()` method supported passing objects with an `as_leaflet_layer()` interface. 
There may be better/cleaner ways to do this, so suggestions are welcome! But, my end goal is to make it easier to go from raster file path to `ipyleaflet.Map` showing tiles like:
```py
from localtileserver import TileClient
from ipyleaflet import Map
client = TileClient('path/to/geo.tif')  # <--- will have `as_leaflet_layer` method
m = Map(center=client.center(), zoom=client.default_zoom)
m.add_layer(client)
m
```

Add support for `as_leaflet_layer` in `Map.add`

---

ipyleaflet/leaflet.py

Fix as_leaflet_layer

---

docs/source/map_and_basemaps/basemaps.rst

Remove HikeBike basemap from the examples shown in the documentation, since it seems not to be maintained anymore.

Remove HikeBike basemap from the examples

---

.github/workflows/update_galata_references.yml

This is only temporary, we should really have an `environment-dev.yml` file at the root that specifies the dev dependencies.

Add pandas to bot

---

js/src/Map.js

For cases where view longitudes are outside `[-180, 180]`.

Fix view bounds

---

ipyleaflet/leaflet.py

This was breaking the map widget when creating a map without setting an initial zoom level. 
Fix #1065 
```python
from ipyleaflet import Map
display(Map())
```

Revert change from #965 that sets the default zoom to None

---

README.md
js/src/Map.js
pyproject.toml

```
import ipyleaflet as l
import ipywidgets as widgets
widgets.Tab(
children=[l.Map()]
)
```
gives in the js console:
`index.es6.js:389 TypeError: Cannot read properties of undefined (reading 'invalidateSize')`
<details>
```
index.es6.js:389 TypeError: Cannot read properties of undefined (reading 'invalidateSize')
at ii._processLuminoMessage (Map.js:470:18)
at ii.processPhosphorMessage (Map.js:442:10)
at e.processMessage (widget.js:722:20)
at f (index.es6.js:442:21)
at Object.n [as sendMessage] (index.es6.js:178:13)
at t.show (index.es6.js:1247:25)
at e._onCurrentChanged (tabpanel.js:271:27)
at c (index.es6.js:459:18)
at e.emit (index.es6.js:416:17)
at t.emit (index.es6.js:99:17)
u @ index.es6.js:389
f @ index.es6.js:445
n @ index.es6.js:178
t.show @ index.es6.js:1247
e._onCurrentChanged …
```

Fix in tab

---

examples/PMTiles.ipynb
ipyleaflet/leaflet.py
js/package.json
js/src/jupyter-leaflet.js
js/src/layers/PMTilesLayer.js
js/src/leaflet.js

[PMTiles](https://github.com/protomaps/PMTiles) is a single-file archive format for tiled data. A PMTiles archive can be hosted on a commodity storage platform such as S3, and enables low-cost, zero-maintenance map applications that are "serverless" - free of a custom tile backend or third party provider. 
Currently, it is challenging to render large vector datasets with ipyleaflet. PMTiles can be a great option for rendering large vector datasets with ipyleaflet. The [folium-pmtiles](https://github.com/jtmiclat/folium-pmtiles) package supports rendering PMTiles with folium. See below for an example. 
This PR tries to add ipyleaflet support for PMTiles. However, I have very limited JavaScript knowledge. I need your help. Thanks. 
@martinRenou @davidbrochart @jtmiclat @bdon …

Add support for PMTiles

---

docs/build-environment.yml
ipyleaflet/leaflet.py
js/src/layers/MarkerCluster.js

Expose more of the MarkerCluster API to ipyleaflet and update the docs with the additional options.

Marker cluster api docs

---

ipyleaflet/leaflet.py
js/package.json
js/src/Map.ts
js/yarn.lock

Updates Leaflet version. Introduces a [breaking change](https://github.com/Leaflet/Leaflet/blob/main/CHANGELOG.md#180-2022-04-18) in Map API.

Leaflet update

---

python/ipyleaflet/pyproject.toml
python/ipyleaflet_core/pyproject.toml
python/jupyter_leaflet/pyproject.toml

I believe this was done accidentally as a part of the recent larger refactor, since testing is still being done on Python 3.8, while it isn't officially supported.

fix: Support for Python 3.8 was removed

---

README.md

The installation instructions still reflect the old repository structure.

fix: outdated installation instructions in README.md

---

python/jupyter_leaflet/src/layers/Circle.ts
python/jupyter_leaflet/src/layers/CircleMarker.ts

Fixes two issues encountered during typescript compilation with newest version of `@types/leaflet`, `1.9.9`.

fix: cast this.get_options to support @types/leaflet@1.9.9

---

docs/controls/index.rst

The documentation for `GeomanDrawControl` was not linked to from the navigation before.

fix(docs): GeomanDrawControl was not included in docs navigation

---

docs/installation/index.rst

install docs still suggest
```
jupyter nbextension enable --py --sys-prefix ipyleaflet
```
which doesn't work anymore because nbextension methods moved to `jupyter_leaflet` without deprecation in #1189. It's unclear from #1189 whether breaking the nbextension name was intentional.
xref #1195

remove broken, deprecated nbextension enable from installation docs

---

python/ipyleaflet/ipyleaflet/leaflet.py

When initializing the Map with a basemap, the basemap `model_id` is not added to the `Map._layer_ids` attribute, resulting in an error when trying to removing the basemap from the map. This PR fixes the bug by adding the basemap layer id to the `Map._layer_ids` attribute
```python
import ipyleaflet
m = ipyleaflet.Map()
m
m.remove(m.layers[0])
```

Add basemap model_id to Map._layer_ids attribute

---

python/ipyleaflet/ipyleaflet/leaflet.py
python/jupyter_leaflet/src/layers/VectorTileLayer.ts

This PR aims to add the ability to use dynamic styling to `VectorTileLayer`. That is, styling may be defined as a function of `properties` and `zoom`. This is possible with [Leaflet.VectorGrid](https://leaflet.github.io/Leaflet.VectorGrid/vectorgrid-api-docs.html), but is not yet implemented in ipyleaflet, because there is currently no way to define python callbacks that can be used by the leaflet map. 
One compromise is to allow the user to define the javascript code for the dynamic style as a string.
Following the [example from the documentation](https://ipyleaflet.readthedocs.io/en/latest/layers/vector_tile.html), here's a simple dynamic style that the user could define for use with `ipyleaflet.VectorTileLayer`: 
```python
jstyle='''{
water:{opacity:0},
places:{opacity:0}, …
```

Improve vector tile layer

---

python/ipyleaflet/ipyleaflet/leaflet.py
python/jupyter_leaflet/src/layers/VectorTileLayer.ts

This PR adds the missing `visible` and `opacity` traits/attributes in vector tile layers, so now it's possible to control the opacity and visibility of these layers using custom widgets.
Here's how it looks like using a custom widget with a checkbox (linked to `visible`) and a slider (linked to `opacity`):
This solves the downstream leafmap [issue](https://github.com/opengeos/leafmap/issues/747) associated with its custom layer control toolbar:

Vector tile layer opacity and visible

---

python/ipyleaflet/ipyleaflet/leaflet.py
python/jupyter_leaflet/src/layers/VectorTileLayer.ts

Vector tile layers can be [rendered](https://leaflet.github.io/Leaflet.VectorGrid/vectorgrid-api-docs.html#svg-vs-canvas) using either `L.canvas.tile` or `L.svg.tile`. Currently, only the canvas option is implemented in ipyleaflet and it's not doing a great job at higher levels of zoom, see for example #1095. 
Here a new `renderer` option was added to `VectorTileLayer`, which can be either `svg` or `canvas`, with the new default being `svg`. 
Here's an example using the `ms-buildings` from Microsoft Planetary Computer, with the new default (svg):
```python
import ipyleaflet
m = ipyleaflet.Map(center=(41.91867,-88.10602), zoom=15)
url = 'https://planetarycomputer.microsoft.com/api/data/v1/vector/collections/ms-buildings/tilesets/global-footprints/tiles/{z}/{x}/{y}'
layer = …
```

Interactive vector tile layers

---

python/jupyter_leaflet/src/Map.ts

This pull request fixes #1224 
Update: also fixes the same issue with other types of zoom:
- doubleClickZoom
- touchZoom
- boxZoom

Add scrollWheelZoom.enable() and disable()

---

python/jupyter_leaflet/src/layers/GeoJSON.ts

This pull request adds event coordinates to the message sent on click and mouseover on `GeoJSON.ts`. 
For example, here we can open a popup on the feature clicked by the user (#1227):
```python
from ipyleaflet import Map, GeoJSON, Popup
from ipywidgets import HTML
m = Map(center=(51.55, -0.09), zoom=10)
geojson_data = {
"type": "FeatureCollection",
"features": [
{
"type": "Feature",
"properties": {
"name": "Polygon A",
"popup_content": "This is Polygon A."
},
"geometry": {
"type": "Polygon",
"coordinates": [[
[-0.1, 51.5],
[-0.1, 51.6],
[-0.05, 51.6],
[-0.05, 51.5],
[-0.1, 51.5]
]]
}
},
{
"type": "Feature",
"properties": {
"name": "Polygon B",
"popup_content": "This is Polygon B."
},
"geometry": {
"type": "Polygon",
"coordinates": [[
[-0.08, 51.48],
[-0.08, 51.52],
[-0.03, 51.52],
[-0.03, …
```

Add event coordinates to GeoJSON message

---

docs/controls/geoman_draw_control.rst
docs/layers/index.rst
python/ipyleaflet/ipyleaflet/leaflet.py

Fixes #1215, see discussion therein.
The possible usage of `pm_ignore=False` is now also included in the in 'Geoman Draw Control' documentation page (with some minor adjustments to existing content)

Make Leaflet-Geoman ignore created layers by default

---

.github/workflows/update_galata_references.yml

This PR updates the conditional logic in the `update-snapshots` GitHub Actions workflow to correctly validate the **comment author's** association with the repository, instead of the **issue/PR author's**.

CI: check comment author association instead of issue author

---

examples/KML.ipynb

fix examples/KML.ipynb because Recent versions of geopandas import fiona dynamically, and gpd.io.file.fiona is initially None.
Supersedes #1141 and resolves merge conflicts

fix `examples/KML.ipynb`

---

python/ipyleaflet/ipyleaflet/leaflet.py
python/jupyter_leaflet/src/layers/TileLayer.ts

Supersedes #1132 while resolving merge conflicts

Update deprecated subdomains for tile.openstreetmap.org

---

python/jupyter_leaflet/src/layers/GeoJSON.ts

Similar to #1249 , this PR updates jupyter_leaflet so that individual layers created by the LeafletGeoJSONModel get the proper `pmIgnore` option -- and disable the `pm` if it's already attached. This fixes the issue that Geoman is able to edit GeoJson layers, even though they inherit the `pm_ignore` from the base Layer class.

fix: geojson layers pmIgnore

---

docs/controls/geoman_draw_control.rst
python/ipyleaflet/ipyleaflet/leaflet.py
python/jupyter_leaflet/src/controls/GeomanDrawControl.ts

feat: add on_click to GeomanDrawControl

---

docs/layers/tooltip.rst
python/ipyleaflet/ipyleaflet/leaflet.py
python/jupyter_leaflet/src/jupyter-leaflet.ts
python/jupyter_leaflet/src/layers/Layer.ts
python/jupyter_leaflet/src/layers/Tooltip.ts

This adds ipyleaflet.Tooltip in order to use [leaflet tooltips](https://leafletjs.com/reference.html#tooltip).
The user can create a "standalone" tooltip at a given location, or bind a Tooltip widget to a Layer, as demonstrated below:
@martinRenou  @arjxn-py  or any other maintainer, please review =)

feat: tooltips
